import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

type SidebarItem = Record<string, unknown> & { type?: string; label?: string; items?: SidebarItem[] };

/**
 * Every item a unique translation key: the path of labels that leads to it.
 *
 * TypeDoc names its categories after the kind of what they hold, so "Classes" and
 * "Interfaces" appear once per module and once per namespace, and v1 and v2 both export a
 * `Collections` class. Docusaurus derives an item's translation key from its label, and
 * refuses to build a translated locale when two keys collide.
 */
function keyed(items: SidebarItem[], parent: string): SidebarItem[] {
  return items.map((item) => {
    const key = `${parent}/${item.label}`;
    if (item.type === "category" && item.items) return { ...item, key, items: keyed(item.items, key) };
    if (item.type === "doc") return { ...item, key };
    return item;
  });
}

/**
 * `docs/api/` is generated by docusaurus-plugin-typedoc on every build (and gitignored), with
 * its own sidebar file beside it. Before the first build it does not exist yet.
 */
function apiSidebar(): SidebarItem[] {
  try {
    // oxlint-disable-next-line typescript/no-require-imports -- the generated sidebar is CommonJS, and may be absent
    return keyed(require("./docs/api/typedoc-sidebar.cjs") as SidebarItem[], "api");
  } catch {
    return [];
  }
}

const sidebars: SidebarsConfig = {
  guides: [
    "intro",
    {
      type: "category",
      label: "SDK",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "API v2",
          collapsed: false,
          items: [
            "sdk/v2/overview",
            "sdk/v2/loaded-rows",
            "sdk/v2/field-projection",
            "sdk/v2/memberships-and-bulk",
            "sdk/v2/lookups",
            "sdk/v2/pagination",
            "sdk/v2/wiki",
            "sdk/v2/errors",
            "sdk/v2/types",
          ],
        },
        "sdk/v1",
        "sdk/authentication",
      ],
    },
    {
      type: "category",
      label: "MCP server",
      collapsed: false,
      items: [
        "mcp/overview",
        "mcp/setup",
        "mcp/task-tools",
        "mcp/work-item-tools",
        "mcp/generic-tools",
        "mcp/configuration",
        "mcp/programmatic",
      ],
    },
    {
      type: "category",
      label: "CLI",
      collapsed: false,
      items: ["cli/overview", "cli/mcp-commands", "cli/windows"],
    },
    "contributing",
  ],
  api: [{ type: "doc", id: "api/index", label: "Overview" }, ...(apiSidebar() as never[])],
};

export default sidebars;
